---
- name: Add download tasks
  include_tasks: download/{{ ansible_pkg_mgr }}.yml

- name: Add install tasks
  include_tasks: install/{{ ansible_pkg_mgr }}.yml

- name: LightHouse | Get lighthouse
  become: true
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: "{{ site_dir }}"
    single_branch: true
    version: master
  notify: Start nginx service
  
- name: LightHouse | Configure nginx
  become: true
  ansible.builtin.template:
    src: lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: Start nginx service

