---
- name: LightHouse | Get distrib nginx rpm
  ansible.builtin.get_url:
    url: "https://nginx.org/packages/centos/7/x86_64/RPMS/nginx-{{ nginx_version }}-1.el7.ngx.x86_64.rpm"
    dest: ./nginx.rpm
    mode: 0755
  check_mode: false
  register: result
  timeout: 60
  until: result is succeeded
  retries: 10

- name: LightHouse | Get distrib git rpm
  ansible.builtin.get_url:
    url: "http://mirror.centos.org/centos/7/os/x86_64/Packages/git-1.8.3.1-23.el7_8.x86_64.rpm"
    dest: ./git.rpm
  register: result
  timeout: 60
  until: result is succeeded
  retries: 10
